apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: secure-queue-scaler
spec:
  scaleTargetRef:
    name: secure-consumer
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: external
      metadata:
        scalerAddress: <SCALER_SERVICE>.<NAMESPACE>.svc.cluster.local:9090
        kubemqAddress: kubemq.default.svc.cluster.local:50000
        queueName: secure-queue
        targetWaiting: "10"
        tls: "true"
        certFile: /certs/ca.pem
        serverOverrideDomain: kubemq.local
      authenticationRef:
        name: kubemq-trigger-auth
